### ISSUE TITLE
Cannot import and use Web Workers while in development mode

### ISSUE THREAD

**Issue by danieleperot** [laravel/vite-plugin#106]
- Laravel Vite Plugin Version: 0.5.0
- Laravel Version: 9.21.0
- Node Version: 16.15.0
- NPM Version: - not applicable -
- Yarn Version: 1.22.18
- Host operating system: Ubuntu 22.04
- Web Browser & Version: Chrome 103
- Running in Sail / Docker: Laravel in Sail, Vite on host

### Description:
Hi everybody! :blush:

I'm trying to setup web workers in my Laravel application.
My goal is to import a web worker and use it inside a Vue component (although this issue will happen when importing the worker in any JS file handled by Vite HMR).

When using the production build, everything works as expected :+1:.

When using the local development build (with Vite being the HRM server), the web worker cannot be imported.

I'm following the official guide: https://vitejs.dev/guide/features.html#web-workers. Four different snippets are provided; I tried all of them but I can't seem to get it working.

Basically, in development mode, Vite cannot import the web worker because it tries to import the script using the wrong url: `http://{laravel base url}/http://{vite server}/{worker}`.

As a current work around I simply build the app using production mode when I need to test the web worker functionality, but this isn't very ideal as I don't have the really nice development experience of Vite HMR and other debugging tools.

### Steps To Reproduce:
1. Create a worker file inside `resources/js` called `worker.js` with the following content:
    ```
    onmessage = (e) => { console.log('Inside web worker!') }
    ```
2. Inside `app.js` add the following snippet:
    ```
    import MyWorker from './worker?worker'
   
    let myWorker = new MyWorker()
    myWorker.postMessage()
    ```
3. Now refresh any page in the browser that uses `app.js`. You should *not* see the console log while running the development mode and you should see in the network tab a 404 error that looks something like this:
    ```
    Request URL: http://laravel.localhost/http://127.0.0.1:5173/resources/js/worker.js?type=module&worker_file
    Request Method: GET
    Status Code: 404 Not found
    ```
    Please note that `laravel.localhost` is simply the base URL in my local env, and I believe the 5173 port number could change with different Vite setups.
    The 404 error **will not** happen when running production mode.

---

Let me know if you need extra details or better instructions on how to set everything up. I believe that if you have any Laravel Sail + Vite development environment you can reproduce the issue.

I will try out few solutions on my own, but I'm not a Vite expert at all so I would appreciate your help :blush:

One last thing: I'm opening this issue in this repository here rather than `vite/vite` because I believe that this is more or less something expected to happen, and that it would be could if it was fixed in this plugin :blush:

Thanks again in advance!

**Comment by jessarcher** [comment]
Hi @danieleperot,

Thanks for reporting this. I have been able to reproduce the issue and I can see what's going on, but I'm not sure what the fix is.

When defining a worker like this in `app.js`:

```js
const worker = new Worker(new URL('./worker.js', import.meta.url))
```

The code served by the Vite dev server looks like this:

```js
const worker = new Worker("/http://127.0.0.1:5173/resources/js/worker.js?type=classic&worker_file")
```

Because of the leading `/`, the browser makes the request to the backend server as you've described (e.g. `http://127.0.0.1:8001/http://127.0.0.1:5173/resources/js/worker.js?type=classic&worker_file`) resulting in the 404.

As an experiment, I tried changing `app.js` to this:

```js
const worker = new Worker("http://127.0.0.1:5173/resources/js/worker.js?type=classic&worker_file")
```

But that gave me this error:

![image](https://user-images.githubusercontent.com/4977161/181132147-4f90f0fa-7741-4be3-bc25-719e254357de.png)

This makes me think that even if we were able to fix the import that it still wouldn't work. I don't really know anything about web workers, so I'm not sure whether it's possible to work around this restriction.

In any case I don't think the issue is caused by anything from this plugin and I don't think there's anything we can do here to fix it. I imagine it would happen with any backend integration where the application is not loaded directly from the Vite dev server.

I'd suggest raising this issue upstream. If there is anything we can do here to fix it, I'm definitely open to it.

In the meantime, you may want to consider running the Vite build with the `--watch` flag so that it will automatically recompile assets on change:

```
npx vite build --watch
```

**Comment by danieleperot** [comment]
Thanks for your work @jessarcher! I can confirm your findings, I went through your same steps and got the same results.

The fact that you can't load a worker from a different origin is the main issue I would say, but of course that's a browser-vendor thing and not fixable by us :smile: 

I will try to see if using `localhost` instead of `127.0.0.1` allows cross-origin web workers: this trick works for example if you need to test service workers locally and you don't have HTTPS.

If that doesn't work I will escalate the issue upstream as you suggested :blush: 

Thanks for the help anyway!

**Comment by jelledv49** [comment]
> 



> Hi @danieleperot,
> 
> Thanks for reporting this. I have been able to reproduce the issue and I can see what's going on, but I'm not sure what the fix is.
> 
> When defining a worker like this in `app.js`:
> 
> ```js
> const worker = new Worker(new URL('./worker.js', import.meta.url))
> ```
> 
> The code served by the Vite dev server looks like this:
> 
> ```js
> const worker = new Worker("/http://127.0.0.1:5173/resources/js/worker.js?type=classic&worker_file")
> ```
> 
> Because of the leading `/`, the browser makes the request to the backend server as you've described (e.g. `http://127.0.0.1:8001/http://127.0.0.1:5173/resources/js/worker.js?type=classic&worker_file`) resulting in the 404.
> 
> As an experiment, I tried changing `app.js` to this:
> 
> ```js
> const worker = new Worker("http://127.0.0.1:5173/resources/js/worker.js?type=classic&worker_file")
> ```
> 
> But that gave me this error:
> 
> ![image](https://user-images.githubusercontent.com/4977161/181132147-4f90f0fa-7741-4be3-bc25-719e254357de.png)
> 
> This makes me think that even if we were able to fix the import that it still wouldn't work. I don't really know anything about web workers, so I'm not sure whether it's possible to work around this restriction.
> 
> In any case I don't think the issue is caused by anything from this plugin and I don't think there's anything we can do here to fix it. I imagine it would happen with any backend integration where the application is not loaded directly from the Vite dev server.
> 
> I'd suggest raising this issue upstream. If there is anything we can do here to fix it, I'm definitely open to it.
> 
> In the meantime, you may want to consider running the Vite build with the `--watch` flag so that it will automatically recompile assets on change:
> 
> ```
> npx vite build --watch
> ```

Did you find a solution for loading a web worker from a different origin? The build command with the watch argument works, but it's not ideal.

**Comment by dreammonkey** [comment]
Any updates here ?
I just ran into this issue on a laravel/inertia/react setup.
It seems running a worker is currently not possible... ?

**Comment by gabrielpetersson** [comment]
having the same issue

**Comment by robjbrain** [comment]
> Did you find a solution for loading a web worker from a different origin? The build command with the watch argument works, but it's not ideal.

Did you ever find a solution to this?

**Comment by dawwwid** [comment]
Hello guys !

Once you have your Laravel project running on port 80 and the ViteJS development server on another port, you won't be able to use the worker (the web browser blocks it).

You could use a proxy, but honestly, I don't feel like modifying the config for that.

So, you need to find a way for ViteJS to compile the worker file and then place it inside the Laravel project so Laravel can use it. That way, you can load the worker from the same domain as the website.

The only solution I found to achieve this is to create a specific config file for my workers.

I created a vite-workers.config.js file with the following code:
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [],
            publicDirectory: `public`,
            buildDirectory: `build/workers`,
        }),
    ],
    build: {
        manifest: false,
        rollupOptions: {
            input: `/resources/js/workers/main-worker.js`,
            output: {
                format: 'iife',
                entryFileNames: 'workers.js',
            },
            watch: {} // !!! IMPORTANT for watching modifications
        },
    }
});
```

IMPORTANT: Make sure to add `watch:{}` so that Vite watches your modifications and doesn't just compile the workers once.

Then, I updated the package.json file:
```json
"workers": "vite build --config vite-workers.config.js",
```

Finally, I run both npm commands (in 2 consoles in PHPSotrm):
`npm run workers
npm run dev`

Now, I can use my worker(s) like this :
```js
const workers = new Worker('/build/workers.js')
```

Et voilà :)

**Comment by wrangelvid** [comment]
> Hello guys !
> ...
> Et voilà :)

That worked for me @dawwwid, thank you!

I ended up making a few modifications to your script that might be worth sharing here:

```javascript
import laravel from "laravel-vite-plugin";
import { defineConfig, loadEnv } from "vite";
import { sync } from "glob";

function getWorkerFiles() {
    return sync("resources/js/**/*.worker.ts").reduce((entries, file) => {
        const name = file.replace(/^.*[\\/]/, "").replace(".ts", "");
        entries[name] = file;
        return entries;
    }, {});
}

export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, process.cwd(), "");
    const watchWorkers = env.WATCH_WORKER === "true" || false;

    return {
        plugins: [
            laravel({
                input: [],
                publicDirectory: "public",
                buildDirectory: "build/workers",
            }),
        ],
        build: {
            manifest: false,
            rollupOptions: {
                input: getWorkerFiles(),
                output: {
                    entryFileNames: "[name].js",
                },
            },
            watch: watchWorkers
                ? {
                      include: "resources/js/**/*.worker.ts",
                  }
                : undefined,
        },
    };
});

```

I opted out of defining watch: {} since it would always watch the build, which I want to avoid during a regular build.
So my package.json file looks like this:
```json
        "dev": "concurrently --kill-others \"vite --host localhost\" \"pnpm worker:watch\"",
        "build": "vite build && vite build --config vite-worker.config.ts",
        "worker:watch": "WATCH_WORKER=true vite build --config vite-worker.config.ts",
```

My import is very similar:
```javascript
const workers = new Worker('/build/[worker_name].worker.js', { type: "module" })
```

While this works, I wish there would be a straight forward way to achieve this with proxies. Unfortunately I couldn't get to work right a way and chose this path.

**Comment by dawwwid** [comment]
Oh great @wrangelvid !!

Not being familiar with quickly, the workers etc ... I had found this solution thanks to a few pieces of docs. But you have completely improved the possibilities, really cool.

Hoping that Laravel | Vite will allow the future to do less gymnastics.
