### ISSUE TITLE
Laragon Hot Reloading

### ISSUE THREAD

**Issue by daugaard47** [laravel/vite-plugin#139]
Does anyone have a working `vite.config.js` file for Laravel and Laragon.
Using:
• Windows 
• Laravel 9
• `"vite": "^3.1.0"` and `"laravel-vite-plugin": "^0.6.0",`

**Main issue: I cannot get the Hot Reloading working in my Laravel project.** 

Going off these docs https://laravel-vite.dev/guide/essentials/development.html#using-http-over-tls I create the `DEV_SERVER_URL` in my Laravel `.env` file, but there is nothing documented on how to actually setup the `vite.config.js` file for Laragon with Hot Reloading. 

Currently my `vite.config.js` file looks like this:
```
import {defineConfig} from 'vite'
import laravel from 'laravel-vite-plugin'

export default defineConfig({
    plugins: [
        laravel([
            'resources/css/app.css',
            'resources/js/app.js',
        ]),
    ],
    refresh: [
        'resources/routes/**',
        'routes/**',
        'resources/views/**',
    ],
    server: {
        https: true,
        type: 'full-reload',
        hmr: {
            host: 'https://mysite.test',
        }
    },
});
```

Outputs:
```
  VITE v3.1.0  ready in 515 ms

  ➜  Local:   https://localhost:5173/
  ➜  Network: use --host to expose

  LARAVEL v9.28.0  plugin v0.6.0

  ➜  APP_URL: https://mysite.test
```

Any help would be appreciated.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by daugaard47** [comment]
If anyone comes across this issue, I got it working by doing the following.
This works with the latest version. Since I use SSL (HTTPS) I had to add my Laragon key and crt.

**vite.config.js**
```
import {defineConfig} from 'vite'
import laravel from 'laravel-vite-plugin'

export default defineConfig({
    server: {
        https: {
            key: "C:/laragon/etc/ssl/laragon.key",
            cert: "C:/laragon/etc/ssl/laragon.crt",
        },
        host: 'localhost',
    },
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
    ],
})
```

**Comment by colbyalbo** [comment]
Just wanted to add to this, in case anyone runs into CORS issues like I did.

My _vite.config.js_ is exactly as the OP's. But I was getting CORS origin errors when using HMR (npm run dev), and the css/js assets were blocked, b/c the assets are coming from `https://127.0.0.1:5173` 
Adding the ASSET_URL to the .env file and setting it to match the APP_URL resolved the issues:

`ASSET_URL="${APP_URL}"`

**Comment by colbyalbo** [comment]
Just a quick follow up, my above work around broke the very next day. I found that there was more pieces to the puzzle.
Note: 
- This may just be needed for Laragon users; I dont know about WSL/Sail/Docker setups.
- The setup below only seems to work in Firefox. I haven't figured out Chrome, which is throwing an incompatible ssl key usage error.

Turns out the ASSET_URL environment variable is not needed at all

my vite.config.js now looks like this

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js',],
            refresh: true,
        }),
        {
            name: 'blade',
            handleHotUpdate({ file, server }) {
                if (file.endsWith('.blade.php')) {
                    server.ws.send({
                        type: 'full-reload',
                        path: '*',
                    });
                }
            },
        }
    ],
    server: {
        https: {
            key: 'C:/laragon/etc/ssl/laragon.key',
            cert: 'C:/laragon/etc/ssl/laragon.crt',
        },
    },

});
```

Then, load the page and confirm the security warning (this is because laragon's SSL cert is self-signed).
At this point the page loads , but the assets don't. Looking at the console, there are CORS errors regarding the 
HMR vite client server at- ```https://127.0.0.1:5173```

So, if you load the vite client url into the browser in a new tab - ```https://127.0.0.1:5173/@vite/client```
You should see the same security warning, confirm it and the laravel/vite page is now allowed to load. 
Now you can go back to your development domain and reload it and it load, and HMR should work.

Note: if you clear you browser cache, you will have to confirm the security exceptions again for both the dev url & the vite client url

If, I figure out a workaround for chrome I'll post it here.
