### ISSUE TITLE
Vite watches the `vendor` folder

### ISSUE THREAD

**Issue by stebogit** [laravel/vite-plugin#152]
- Laravel Vite Plugin Version: 0.6.1
- Laravel Version: 9.31.0
- Node Version: 16.17.1
- NPM Version: 8.15.0
- Host operating system: Linux (Homestead, Ubuntu 18.04.5 LTS)
- Web Browser & Version: -
- Running in Sail / Docker: No

### Description:
Just installed Breeze (`php artisan breeze:install`) and tried to serve the assets (`npm run dev`) and I got this error, suggesting vite is watching the `vendor` folder (which I assume should be ignored, by default):

![Screen Shot 2022-09-30 at 2 56 43 PM](https://user-images.githubusercontent.com/12717225/193361872-eda2548e-544d-4fad-9c84-aa875de3bf41.png)

The command `npm run build` works fine anyway.

### Steps To Reproduce:
This is my config, I tried to even defining a more restrictive `refresh` path:
```js
export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            // none of these work
            // refresh: true,
            // refresh: false,
            refresh: [
                'resources/**',
            ],
        }),
    ],
});

```

**Comment by timacdonald** [comment]
Hi @stebogit,

I'm unable to reproduce this with a fresh Laravel installation. I can only get Vite to watch the vendor directory if I explicitly configure it to watch it.

Can you create a reproduction repository for this and we can re-open the issue?

```
laravel new bug-report --github="--public"
```

**Comment by michaelk83** [comment]
There are multiple users affected by this, see https://github.com/laravel/framework/discussions/46928 . But you need to have enough files in `vendor/` or a low enough watches limit to trigger the error. The latter would depend on your system configuration. More recent linux system may have a higher limit set by default.
https://stackoverflow.com/a/67171846/15047974
https://stackoverflow.com/a/55543310/15047974

In any case, even if the watches limit is high enough, watching thousands of irrelevant files can be slow, so the `vendor/` folder (and `storage/`, I guess) should not be listened to by default. I don't know if this should be addressed in the plugin or framework, but I've found this issue here, so am linking to the [discussion above](https://github.com/laravel/framework/discussions/46928).

**Comment by timacdonald** [comment]
I'm not against the idea of ignoring some directories by default. As Vite ignores `node_modules` by default I think it could make sense for us to ignore `vendor` by default, along with some other directories(?).

The main problem I see is the globing patterns, such as `**/vendor/**`, would ignore any directory named `vendor`. That is unfortunate as Laravel publishes assets to the `public/vendor` directory.

That being said, as they are "vendor" files there is potential that it also makes sense to ignore them by default as you likely are not changing them inline.

<img width="288" alt="Screenshot 2024-02-12 at 12 50 10 pm" src="https://github.com/laravel/vite-plugin/assets/24803032/71b1df28-a73e-4725-9e22-941cbce1141c">

**Comment by michaelk83** [comment]
If `**/vendor/**` is not optimal, I think `/vendor/**` should also work.
https://vitejs.dev/guide/features#glob-import-caveats

Or:
```
'**/vendor/**',
'!/public/vendor/**'
```
