### ISSUE TITLE
Vite compilation is getting stuck

### ISSUE THREAD

**Issue by RahulDey12** [laravel/vite-plugin#157]
- Laravel Vite Plugin Version: 0.7
- Laravel Version: 9.x
- Node Version: 16.13.2
- NPM Version: 8.3.2
- Host operating system: AL2 (Amazon Linux 2)
- Running in Sail / Docker: No

### Description:
Hi, I am using Laravel and Vite for a production application that currently has 200GB of data in the `storage/app` directory, and then when I am trying to build it is getting stuck. But if I build after deleting/unmounting that directory it is building like butter. My thought is that it is scanning the whole application before the building which is why it is taking too much time cuz there is too much data to scan.

If there is any process to ignore the storage directory scan at the time of building that will be enough to resolve the issue, Thank You.

### Steps To Reproduce:
I don't think there is any easy way to reproduce the issue unless you have that much data in any directory and you are building on the same server.

But you can check this behavior by installing [inotify-tools](https://github.com/inotify-tools/inotify-tools)

- Install [inotify-tools](https://github.com/inotify-tools/inotify-tools)
- Run from laravel application `inotifywatch -r ./storage` and leave
- Any other shell run `npm run build`
- Now come back to inotifywatch tab and check the stats. You can see it literally accessed every file in the storage directory.

**Comment by jessarcher** [comment]
Hey,

This sounds like an issue with Vite/Rollup rather than this plugin. I'm not aware of anything we could do to ignore that directory.

I tested your inotifywatch suggestion _without_ this plugin (and an empty `index.html` - the default Vite entry point) and the behaviour is the same. I then tested `npx rollup index.html` and it still hits everything in the storage directory. I can't see any rollup configuration options that might help :(

If you can find something that might help, feel free to open another issue or PR.
