### ISSUE TITLE
Manifest.json, wrong chunk name when dynamic import has other dynamic imports

### ISSUE THREAD

**Issue by aktasumut34** [laravel/vite-plugin#198]
- Laravel Vite Plugin Version: 0.7.2
- Laravel Version: 9.44
- Node Version: 18.13.0
- NPM Version: 8.19.3
- Host operating system: Linux
- Web Browser & Version: Chrome 109.0.5414.12
- Running in Sail / Docker: No

### Description:

I'm using `resolvePageComponent` for inertia like this:
```
resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'))
```
in my `ExamplePage.vue` i have dynamic import
```
let x = defineAsyncComponent(() => import('@/Components/X.vue')),
```
and i have `ExamplePage2.vue`, i haven't any dynamic import on it.

After building js bundle, everything works fine if i first go ExamplePage2 then ExamplePage, but when i refresh page on ExamplePage.vue, it throws
```
Unable to locate file in Vite manifest: resources/js/Pages/ExamplePage.vue
```

When there is entry for ExamplePage2.vue, ExamplePage2.vue converted to `_Example-{hash}.js`
Here is 'short-version' of generated manifest.json file. 

```
{
  "resources/js/Pages/ExamplePage2.vue": {
    "file": "assets/example-page-2-e517633b.js",
    "src": "resources/js/Pages/ExamplePage2.vue",
    "isDynamicEntry": true,
  },
  "_ExamplePage-85439fa4.js": {
    "file": "assets/ExamplePage-85439fa4.js",
    "isDynamicEntry": true,
    "dynamicImports": [
      "resources/js/Components/X.vue",
    ]
  },
  "resources/js/app.ts": {
    "file": "assets/app-81fa5b5c.js",
    "src": "resources/js/app.ts",
    "isEntry": true,
    "dynamicImports": [
      "_ExamplePage-85439fa4.js",
      "resources/js/Pages/ExamplePage2.vue",
    ],
  }
}
```

**Comment by timacdonald** [comment]
Hey there,

Can you please create a minimal reproduction for this and we take a closer look?

```
laravel new bug-report --github="--public"
```

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Comment by travisricks** [comment]
I came across this issue via Google because I’m running into the exact same problem.

I’m using Inertia, and when a page component (e.g. ExamplePage.vue) imports any child components using Vue’s `defineAsyncComponent`, the route fails with a 500 error:

`Unable to locate file in Vite manifest: resources/js/Pages/ExamplePage.vue`

Looking at the generated manifest, I can see that the entry for `resources/js/Pages/ExamplePage.vue` is missing. Instead, it gets renamed to something like `ExamplePage-XXXX.js`, unlike other pages that don’t use defineAsyncComponent — those are correctly listed with their .vue path in the manifest.

If I remove the defineAsyncComponent usage from the page and rebuild, the error goes away and the manifest includes the expected .vue path again.

I’ll work on a minimal repro later today.
