### ISSUE TITLE
Update typescript dependency?

### ISSUE THREAD

**Issue by Azeirah** [laravel/vite-plugin#236]
The typescript version is pinned at ^4.6, I would prefer a more recent version. For instance I'm using the HTMLDialogElement type which is supported starting from 4.7.

**Comment by jessarcher** [comment]
Hey @Azeirah,

TypeScript is only a dev dependency on this package, required for building the plugin, but shouldn't impact what you use in your application.

The dev dependency is also `^4.6.4`, which allows any version `>= 4.6.4` and `< 5`. Please see https://semver.npmjs.com/ for more info.

Are you sure it's this package that's affecting you?

**Comment by Azeirah** [comment]
Ah ok, I misinterpreted the `^` version operator then. I'll take a look at the other dependencies and see what's pinning my TypeScript at an older version.

Other than that, is there a particular reason not to support TypeScript 5+ as well? If nothing is holding it back it would still be nice to have the most recent features, especially the performance increases would be nice :)

**Comment by jessarcher** [comment]
All good :slightly_smiling_face: 

There's nothing in this package that should prevent you from using TypeScript 5. For example, in the TypeScript presets of the [Laravel Breeze](https://laravel.com/docs/10.x/starter-kits#laravel-breeze) starter kit, [we install TypeScript 5](https://github.com/laravel/breeze/blob/1.x/src/Console/InstallsInertiaStacks.php#L39) for you.

The TypeScript dependency in this project is essentially for internal use just to transpile the Laravel Vite plugin so we can deploy it to npm. It's probably worth updating to TypeScript 5 at some point, but the plugin is quite small and probably wouldn't see much benefit from a later version.

You could try running `npm why typescript` to see which of your packages depends on which versions.

If you do confirm a problem caused by this plugin, please feel free to open another issue.
